name: Development
run-name: Compilation & Quality Checks
on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install & Compile
        run: |
          npm install
          npm run-script build
  frontend-unit-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: ViTest
        run: |
          npm ci
          npm run-script test
#  cypress-e2e:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#      - name: Cypress E2E
#        uses: cypress-io/github-action@v6
#        with:
#          build: npm run build
#          start: npm run dev
#          browser: chrome